# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0aef171ff7fc13d8ed8d4ac310f88a82bc9ebd3701f377eb8d3ccd53d4dc0240e62736b67afc4750a59d27a6a995531ecda0fcc71ccebf08c2530b7f50031bff

test:
  secret_key_base: 7218350c01b8ea2b1633d4f804fe2dfa32b8ac94a724ad408124c09adb09c8050c707173b47be5f4643afdf96840e9e38feec6fe25457a3590c055f73f1fa62e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
